spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: sunzhaoguo
mybatis:
   mapperLocations: classpath:/mapper/*.xml
